<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body style="border-radius:10;">
<form>
<?php
header("refresh:0.1");
$x=rand(10,799);
$r=rand(111111,999999);
$r1=rand(111111,999999);
$r2=rand(111111,999999);
$r3=rand(111111,999999);
$r4=rand(111111,999999);
$r5=rand(111111,999999);
$r6=rand(111111,999999);
$y=rand(10,899);
$y1=rand(10,999);
$y2=rand(10,899);
$y3=rand(10,899);
$y4=rand(10,899);
$y5=rand(10,899);
$y6=rand(10,899);
$y7=rand(10,899);
$y8=rand(10,899);

echo"
<div style='width:".$y6."px; height:20px; background:#$r;  float:left; border-radius:10px;;'></div><br>
<div style='width:".$y5."px; height:20px; background:#$r1;  float:right; border-radius:10px'></div><br>
<div style='width:".$y4."px; height:20px; background:#$r2;  float:right; border-radius:10px'></div><br>
<div style='width:".$y3."px; height:20px; background:#$r3; float:left; border-radius:10px;'></div><br>
<div style='width:".$y2."px; height:20px; background:#$r4;  float:right; border-radius:10px'></div><br>
<div style='width:".$y1."px; height:20px; background:#$r5; float:left; border-radius:10px;'></div><br>
<div style='width:".($y7)."px; height:20px; background:#$r6;  float:right; border-radius:10px'></div><br>
<div style='width:".($y6)."px; height:20px; background:#$r1; float:left; border-radius:10px;'></div><br>
<div style='width:".($y5)."px; height:20px; background:#$r5;  float:right; border-radius:10px'></div><br>
<div style='width:".($y4)."px; height:20px; background:#$r4; float:left; border-radius:10px;'></div><br>
<div style='width:".($y3)."px; height:20px; background:#$r3;  float:right; border-radius:10px'></div><br>
<div style='width:".($y2)."px; height:20px; background:#$r2; float:left; border-radius:10px;'></div><br>
<div style='width:".($y1)."px; height:20px; background:#$r1;  float:right; border-radius:10px'></div><br>
<div style='width:".($y2)."px; height:20px; background:#$r2; float:left; border-radius:10px;'></div><br>
<div style='width:".($y3)."px; height:20px; background:#$r3;  float:right; border-radius:10px'></div><br>
<div style='width:".($y4)."px; height:20px; background:#$r4; float:left; border-radius:10px;'></div><br>
<div style='width:".($y5)."px; height:20px; background:#$r5;  float:right; border-radius:10px'></div><br>
<div style='width:".($y6)."px; height:20px; background:#$r6; float:left; border-radius:10px;'></div><br>
<div style='width:".($y7)."px; height:20px; background:#$r3;  float:right; border-radius:10px'></div><br>
<div style='width:".($y6)."px; height:20px; background:#$r4; float:left; border-radius:10px;'></div><br>
<div style='width:".($y5)."px; height:20px; background:#$r5;  float:right; border-radius:10px'></div><br>
<div style='width:".($y4)."px; height:20px; background:#$r6; float:left; border-radius:10px;'></div><br>
<div style='width:".($y3)."px; height:20px; background:#$r5;  float:right; border-radius:10px'></div><br>
<div style='width:".($y2)."px; height:20px; background:#$r4; float:left; border-radius:10px;'></div><br>
<div style='width:".($y1)."px; height:20px; background:#$r3;  float:right; border-radius:10px'></div><br>
<div style='width:".($y2)."px; height:20px; background:#$r2; float:left; border-radius:10px;'></div><br>
<div style='width:".($y6)."px; height:20px; background:#$r1;  float:right; border-radius:10px'></div><br>
<div style='width:".($y5)."px; height:20px; background:#$r5; float:left; border-radius:10px;'></div><br>
<div style='width:".($y4)."px; height:20px; background:#$r4;  float:right; border-radius:10px'></div><br>
<div style='width:".($y3)."px; height:20px; background:#$r3; float:left; border-radius:10px;'></div><br>
<div style='width:".($y2)."px; height:20px; background:#$r2;  float:right; border-radius:10px'></div><br>
<div style='width:".($y1)."px; height:20px; background:#$r1; float:left; border-radius:10px;'></div><br>
<div style='width:".($y3)."px; height:20px; background:#$r2;  float:right; border-radius:10px'></div><br>
<div style='width:".($y4)."px; height:20px; background:#$r3; float:left; border-radius:10px;'></div><br>
<div style='width:".($y5)."px; height:20px; background:#$r4;  float:right; border-radius:10px'></div><br>
<div style='width:".($y6)."px; height:20px; background:#$r5; float:left; border-radius:10px;'></div><br>
<div style='width:".($y7)."px; height:20px; background:#$r6;  float:right; border-radius:10px'></div><br>
<div style='width:".($y6)."px; height:20px; background:#$r5; float:left; border-radius:10px;'></div><br>
<div style='width:".($y5)."px; height:20px; background:#$r4;  float:right; border-radius:10px'></div><br>
<div style='width:".($y4)."px; height:20px; background:#$r3; float:left; border-radius:10px;'></div><br>
<div style='width:".($y3)."px; height:20px; background:#$r2;  float:right; border-radius:10px'></div><br>
<div style='width:".($y2)."px; height:20px; background:#$r1; float:left; border-radius:10px;'></div><br>
<div style='width:".($y1)."px; height:20px; background:#$r5;  float:right; border-radius:10px '></div><br>
<div style='width:".$y6."px; height:20px; background:#$r;  float:left; border-radius:10px;'></div><br>
<div style='width:".$y5."px; height:20px; background:#$r1;  float:right; border-radius:10px'></div><br>
<div style='width:".$y4."px; height:20px; background:#$r2; float:left; border-radius:10px;'></div><br>
<div style='width:".$y3."px; height:20px; background:#$r3;  float:right; border-radius:10px'></div><br>
<div style='width:".$y2."px; height:20px; background:#$r4; float:left; border-radius:10px;'></div><br>
<div style='width:".$y1."px; height:20px; background:#$r5;  float:right; border-radius:10px'></div><br>
<div style='width:".($y7)."px; height:20px; background:#$r6; float:left; border-radius:10px;'></div><br>
<div style='width:".($y6)."px; height:20px; background:#$r1;  float:right; border-radius:10px'></div><br>
<div style='width:".($y5)."px; height:20px; background:#$r5;  float:right; border-radius:10px'></div><br>
<div style='width:".($y4)."px; height:20px; background:#$r4; float:left; border-radius:10px;'></div><br>
<div style='width:".($y3)."px; height:20px; background:#$r3;  float:right; border-radius:10px'></div><br>
<div style='width:".($y2)."px; height:20px; background:#$r2; float:left; border-radius:10px;'></div><br>
<div style='width:".($y1)."px; height:20px; background:#$r1;  float:right; border-radius:10px'></div><br>
<div style='width:".($y2)."px; height:20px; background:#$r2; float:left; border-radius:10px;'></div><br>
<div style='width:".($y3)."px; height:20px; background:#$r3;  float:right; border-radius:10px'></div><br>
<div style='width:".($y4)."px; height:20px; background:#$r4; float:left; border-radius:10px;'></div><br>
<div style='width:".($y5)."px; height:20px; background:#$r5;  float:right; border-radius:10px'></div><br>
<div style='width:".($y6)."px; height:20px; background:#$r6; float:left; border-radius:10px;'></div><br>
<div style='width:".($y7)."px; height:20px; background:#$r3;  float:right; border-radius:10px'></div><br>
<div style='width:".($y6)."px; height:20px; background:#$r4; float:left; border-radius:10px;'></div><br>
<div style='width:".($y5)."px; height:20px; background:#$r5;  float:right; border-radius:10px'></div><br>
<div style='width:".($y4)."px; height:20px; background:#$r6; float:left; border-radius:10px;'></div><br>
<div style='width:".($y3)."px; height:20px; background:#$r5;  float:right; border-radius:10px'></div><br>
<div style='width:".($y2)."px; height:20px; background:#$r4; float:left; border-radius:10px;'></div><br>
<div style='width:".($y1)."px; height:20px; background:#$r3;  float:right; border-radius:10px'></div><br>
<div style='width:".($y2)."px; height:20px; background:#$r2; float:left; border-radius:10px;'></div><br>
<div style='width:".($y6)."px; height:20px; background:#$r1;  float:right; border-radius:10px'></div><br>
<div style='width:".($y5)."px; height:20px; background:#$r5; float:left; border-radius:10px;'></div><br>
<div style='width:".($y4)."px; height:20px; background:#$r4;  float:right; border-radius:10px'></div><br>
<div style='width:".($y3)."px; height:20px; background:#$r3; float:left; border-radius:10px;'></div><br>
<div style='width:".($y2)."px; height:20px; background:#$r2;  float:right; border-radius:10px'></div><br>
<div style='width:".($y1)."px; height:20px; background:#$r1; float:left; border-radius:10px;'></div><br>
<div style='width:".($y3)."px; height:20px; background:#$r2;  float:right; border-radius:10px'></div><br>
<div style='width:".($y4)."px; height:20px; background:#$r3; float:left; border-radius:10px;'></div><br>
<div style='width:".($y5)."px; height:20px; background:#$r4;  float:right; border-radius:10px'></div><br>
<div style='width:".($y6)."px; height:20px; background:#$r5; float:left; border-radius:10px;'></div><br>
<div style='width:".($y7)."px; height:20px; background:#$r6;  float:right; border-radius:10px'></div><br>
<div style='width:".($y6)."px; height:20px; background:#$r5; float:left; border-radius:10px;'></div><br>
<div style='width:".($y5)."px; height:20px; background:#$r4;  float:right; border-radius:10px'></div><br>
<div style='width:".($y4)."px; height:20px; background:#$r3; float:left; border-radius:10px;'></div><br>
<div style='width:".($y3)."px; height:20px; background:#$r2;  float:right; border-radius:10px'></div><br>
<div style='width:".($y2)."px; height:20px; background:#$r1; float:left; border-radius:10px;'></div><br>
<div style='width:".($y1)."px; height:20px; background:#$r5;  float:right; border-radius:10px '></div><br>
<div style='width:".$y6."px; height:20px; background:#$r;  float:left; border-radius:10px;'></div><br>
<div style='width:".$y5."px; height:20px; background:#$r1;  float:right; border-radius:10px'></div><br>
<div style='width:".$y4."px; height:20px; background:#$r2; float:left; border-radius:10px;'></div><br>
<div style='width:".$y3."px; height:20px; background:#$r3;  float:right; border-radius:10px'></div><br>
<div style='width:".$y2."px; height:20px; background:#$r4; float:left; border-radius:10px;'></div><br>
<div style='width:".$y1."px; height:20px; background:#$r5;  float:right; border-radius:10px'></div><br>
<div style='width:".($y7)."px; height:20px; background:#$r6; float:left; border-radius:10px;'></div><br>
<div style='width:".($y6)."px; height:20px; background:#$r1;  float:right; border-radius:10px'></div><br>
<div style='width:".($y5)."px; height:20px; background:#$r5; float:left; border-radius:10px;'></div><br>
<div style='width:".($y4)."px; height:20px; background:#$r4;  float:right; border-radius:10px'></div><br>
<div style='width:".($y3)."px; height:20px; background:#$r3; float:left; border-radius:10px;'></div><br>
<div style='width:".($y2)."px; height:20px; background:#$r2;  float:right; border-radius:10px'></div><br>
<div style='width:".($y1)."px; height:20px; background:#$r1; float:left; border-radius:10px;'></div><br>
<div style='width:".($y2)."px; height:20px; background:#$r2;  float:right; border-radius:10px'></div><br>
<div style='width:".($y3)."px; height:20px; background:#$r3; float:left; border-radius:10px;'></div><br>
<div style='width:".($y4)."px; height:20px; background:#$r4;  float:right; border-radius:10px'></div><br>
<div style='width:".($y5)."px; height:20px; background:#$r5; float:left; border-radius:10px;'></div><br>
<div style='width:".($y6)."px; height:20px; background:#$r6;  float:right; border-radius:10px'></div><br>
<div style='width:".($y7)."px; height:20px; background:#$r3; float:left; border-radius:10px;'></div><br>
<div style='width:".($y6)."px; height:20px; background:#$r4;  float:right; border-radius:10px'></div><br>
<div style='width:".($y5)."px; height:20px; background:#$r5; float:left; border-radius:10px;'></div><br>
<div style='width:".($y4)."px; height:20px; background:#$r6;  float:right; border-radius:10px'></div><br>
<div style='width:".($y3)."px; height:20px; background:#$r5; float:left; border-radius:10px;'></div><br>
<div style='width:".($y2)."px; height:20px; background:#$r4;  float:right; border-radius:10px'></div><br>
<div style='width:".($y1)."px; height:20px; background:#$r3; float:left; border-radius:10px;'></div><br>
<div style='width:".($y2)."px; height:20px; background:#$r2;  float:right; border-radius:10px'></div><br>
<div style='width:".($y6)."px; height:20px; background:#$r1; float:left; border-radius:10px;'></div><br>
<div style='width:".($y5)."px; height:20px; background:#$r5;  float:right; border-radius:10px'></div><br>
<div style='width:".($y4)."px; height:20px; background:#$r4; float:left; border-radius:10px;'></div><br>
<div style='width:".($y3)."px; height:20px; background:#$r3;  float:right; border-radius:10px'></div><br>
<div style='width:".($y2)."px; height:20px; background:#$r2; float:left; border-radius:10px;'></div><br>
<div style='width:".($y1)."px; height:20px; background:#$r1;  float:right; border-radius:10px'></div><br>
<div style='width:".($y3)."px; height:20px; background:#$r2; float:left; border-radius:10px;'></div><br>
<div style='width:".($y4)."px; height:20px; background:#$r3;  float:right; border-radius:10px'></div><br>
<div style='width:".($y5)."px; height:20px; background:#$r4; float:left; border-radius:10px;'></div><br>
<div style='width:".($y6)."px; height:20px; background:#$r5;  float:right; border-radius:10px'></div><br>
<div style='width:".($y7)."px; height:20px; background:#$r6; float:left; border-radius:10px;'></div><br>
<div style='width:".($y6)."px; height:20px; background:#$r5;  float:right; border-radius:10px'></div><br>
<div style='width:".($y5)."px; height:20px; background:#$r4; float:left; border-radius:10px;'></div><br>
<div style='width:".($y4)."px; height:20px; background:#$r3;  float:right; border-radius:10px'></div><br>
<div style='width:".($y3)."px; height:20px; background:#$r2; float:left; border-radius:10px;'></div><br>
<div style='width:".($y2)."px; height:20px; background:#$r1;  float:right; border-radius:10px'></div><br>
<div style='width:".($y1)."px; height:20px; background:#$r5; float:left; border-radius:10px; '></div><br>
<div style='width:".($y2)."px; height:20px; background:#$r2;  float:right; border-radius:10px'></div><br>
<div style='width:".($y1)."px; height:20px; background:#$r1; float:left; border-radius:10px;'></div><br>
<div style='width:".($y3)."px; height:20px; background:#$r2;  float:right; border-radius:10px'></div><br>
<div style='width:".($y4)."px; height:20px; background:#$r3; float:left; border-radius:10px;'></div><br>
<div style='width:".($y5)."px; height:20px; background:#$r4;  float:right; border-radius:10px'></div><br>
<div style='width:".($y6)."px; height:20px; background:#$r5; float:left; border-radius:10px;'></div><br>
<div style='width:".($y7)."px; height:20px; background:#$r6;  float:right; border-radius:10px'></div><br>
<div style='width:".($y6)."px; height:20px; background:#$r5; float:left; border-radius:10px;'></div><br>
<div style='width:".($y5)."px; height:20px; background:#$r4;  float:right; border-radius:10px'></div><br>
<div style='width:".($y4)."px; height:20px; background:#$r3; float:left; border-radius:10px;'></div><br>
<div style='width:".($y3)."px; height:20px; background:#$r2;  float:right; border-radius:10px'></div><br>
<div style='width:".($y2)."px; height:20px; background:#$r1; float:left; border-radius:10px;'></div><br>
<div style='width:".($y1)."px; height:20px; background:#$r5;  float:right; border-radius:10px '></div><br>
<div style='width:".($y2)."px; height:20px; background:#$r2; float:left; border-radius:10px;'></div><br>
<div style='width:".($y1)."px; height:20px; background:#$r1;  float:right; border-radius:10px'></div><br>
<div style='width:".($y3)."px; height:20px; background:#$r2; float:left; border-radius:10px;'></div><br>
<div style='width:".($y4)."px; height:20px; background:#$r3;  float:right; border-radius:10px'></div><br>
<div style='width:".($y5)."px; height:20px; background:#$r4; float:left; border-radius:10px;'></div><br>
<div style='width:".($y6)."px; height:20px; background:#$r5;  float:right; border-radius:10px'></div><br>
<div style='width:".($y7)."px; height:20px; background:#$r6; float:left; border-radius:10px;'></div><br>
<div style='width:".($y6)."px; height:20px; background:#$r5;  float:right; border-radius:10px'></div><br>
<div style='width:".($y5)."px; height:20px; background:#$r4; float:left; border-radius:10px;'></div><br>
<div style='width:".($y4)."px; height:20px; background:#$r3;  float:right; border-radius:10px'></div><br>
<div style='width:".($y4)."px; height:20px; background:#$r3; float:left; border-radius:10px;'></div><br>
";
?>
</form>
</body>
</html>